### ISSUE TITLE
bug:  Safari Performance very poor.

### ISSUE THREAD

**Issue by darkkilltec** [saadeghi/daisyui#2404]
### 1. What version of daisyUI are you using?

v3.9.1

### 2. Describe your issue

There is a real performance issue on Safari Browser, even just going to daisyuis website and hover over the menu shows very high cpu usage and lag. This does not happen on any other browser, so this is a specific safari issue. It seems to be something with transition and gradients. Can please anyone check this out?

### 3. What browsers are you seeing the problem on?

Safari

### 4. Reproduction URL

https://daisyui.com

**Comment by saadeghi** [comment]
Thanks.  
The performance on Safari is now improved.

**Comment by ivanbara** [comment]
Doesn't seem to be (or maybe it was even worse before?). Any interactive elements, like Accordion, Collapse, Countdown, stutter like crazy.

**Comment by saadeghi** [comment]
Can you share your system information?
- OS version
- Safari version
- Which Mac computer is it?

**Comment by ivanbara** [comment]
MacOS Sonoma 14.1.2
Safari Version 17.1.2
Same issues on all: M1, M2, M3 macbook pro/mini/studio

**Comment by vinidiktov** [comment]
I've come to this issue to confirm that the performance issues are still not resolved.

For example, if I go here: https://daisyui.com/components/navbar/ hove over any element or click any clickable elements, the response will be noticeably laggy (up to 1 second response time).

For example, try hovering your mouse pointer over the buttons here or clicking the buttons:
<img width="913" alt="Screenshot 2024-01-10 at 11 56 13" src="https://github.com/saadeghi/daisyui/assets/75051/83a50004-e777-452c-981a-7ea530e4a627">

macOS Sonoma 14.2.1
Safari 17.2.1
MacBook Air M1

**Comment by j0sh** [comment]
This is still an issue today with Safari. The DaisyUI website uses too much CPU which makes things lag and stutter when navigating the site - scrolling, switching tabs in the code examples, etc.

I like using DaisyUI but it is not a good look for trying to showcase the toolkit. I have actually found myself avoiding looking up things on the website sometimes because I don't want to deal with the slow performance.

MacOS Monterey 12.6.6
Safari 16.5
Macbook Pro (Intel)

<img width="420" alt="image" src="https://github.com/saadeghi/daisyui/assets/292510/4254f67b-5cdc-4509-873e-33c72fb5c61a">

**Comment by saadeghi** [comment]
> <img alt="image" width="420" src="https://private-user-images.githubusercontent.com/292510/314649013-4254f67b-5cdc-4509-873e-33c72fb5c61a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTE4OTQsIm5iZiI6MTcxMTQ1MTU5NCwicGF0aCI6Ii8yOTI1MTAvMzE0NjQ5MDEzLTQyNTRmNjdiLTVjZGMtNDUwOS04NzNlLTMzYzcyZmI1YzYxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMTEzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWQzODU5OTBiMTAzMWRhNTllMDdiYzgzMTUxNzI0MzMyOTA3MTIzNTJjZDM0OGY1Y2E3YTBmMDNhMTFhZDRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X6ThqwCihb0bjG87bLebXGvvmCy13awjJKhOCybc1hE">

This is not normal.  
Here's CPU usage on my MacBook Air 2022  
And there are no lags or delays  

<img width="394" alt="Screenshot 2024-03-26 at 2 15 24 PM" src="https://github.com/saadeghi/daisyui/assets/7342023/36e3bd76-9aa6-4f63-a66b-09bc5f7527ba">

**Comment by optikfluffel** [comment]
Same here, some things seem really laggy. Most noticeable on the Countdown page. But "Safari Graphics and Media" is the CPU hog for me.

macOS Sonoma 14.4.1
Safari 17.4.1
MacBook Air M1

![Screenshot of Activity Monitor](https://github.com/saadeghi/daisyui/assets/379915/e1f96ca9-61ab-446c-931a-ecb57696c430)

<img width="960" alt="Screenshot 2024-04-17 at 15 26 21" src="https://github.com/saadeghi/daisyui/assets/379915/9a5ca824-f62a-49fd-88fa-1a7f058cf728">

https://github.com/saadeghi/daisyui/assets/379915/9f9e0902-5573-4146-9f1c-2ecc366b8cdd

**Comment by codepilotsf** [comment]
This issue should not be closed -- I'm having the *exact* same problem. Especially the countdown component – latest Safari, MacBook Air M2.

**Comment by saadeghi** [comment]
The issue was about the transitions used on daisyUI websites and it was fixed.  
Tbe following comments are about different things and has nothing to do with the original issue so it doesn't make sense to reopen it.  

Sometimes there are performance bugs on some versions of browsers and they will be fixed in the following updates.  
Sometimes the performance issue is coming from lack of resources (maybe there's not enough RAM/GPU/CPU... available.

But I have to mention that hover styles are basic color changes and countdown is a simple 2D CSS transform. They are not crazy 3D processes or heavy animations or blur effects, etc. If your browser can not run it, the problem is your browser/computer. Hopefully they will fix it in the next browser update.
Unfortunately there's nothing I can do about it. Since I didn't use any heavy animations for them. They are simple CSS hover and simple CSS transforms.

**Comment by codepilotsf** [comment]
Just FYI, my issue is actually the same (related to original issue). The DaisyUI website forces Safari to a crawl. I have a 1 year old M2 MacBook with 24 GB RAM and fresh MacOS install and latest Safari – so I don't think it's my machine/browser. I also don't have this issue on any other websites but consistently have it every time I visit daisyui.com – just as others have reported and continue to report. It's obviously up to you to determine whether this is important or not -- but just please be aware that is in fact a persistent issue.

**Comment by optikfluffel** [comment]
@saadeghi I may have found a solution to this. Instead of using `top: calc(var(--value) * -1em)` to animate the countdowns, which invalidates the layout every time the `value` changes, you could use `transform: translateY(calc(var(--value) * -1em))` and give the `:before` some `display: inline-flex`, because this doesn't work with `display: inline`.

With this the animations run buttery smooth in my Safari. 😊

**Comment by mxz7** [comment]
Website is still incredibly laggy on Safari, no matter what component I'm looking at it seems.

M1 Pro

**Comment by shabman** [comment]
Hi, this issue still persists for me, every animation is incredibly laggy and slow.

Running:
- Safari 17.6
- macOS 14..6.1
- M2 Chip
- 8GB Ram

**Comment by vad1ym** [comment]
Hi, I'm experiencing a similar issue and found that the cause lies in the banner at the bottom of the website. Safari doesn't handle well `filter: blur` (or `backdrop-filter: blur`). 

Forcing GPU acceleration by adding `transform: translate3d(0, 0, 0);` to the banner card is resolving the problem for me

Banner with blur:
<img width="931" alt="image" src="https://github.com/user-attachments/assets/cdd0c7d6-f753-4e3d-ae64-41a5ef913e37">
