### ISSUE TITLE
docs: Custom themes don't work on Firefox

### ISSUE THREAD

**Issue by sveltarne** [saadeghi/daisyui#2503]
### On which page do you see this issue?

https://daisyui.com/

### Describe the issue

When i select any custom theme, it looks the same as it did before. Additionally, all the themes look the same in the theme chooser dropdown.

### What browsers are you seeing the problem on?

Firefox

**Comment by saadeghi** [comment]
Which version of Firefox?

**Comment by sveltarne** [comment]
119

**Comment by alexzvn** [comment]
It seems data-theme not work well in Firefox.

**Comment by sveltarne** [comment]
i guess.. but it worked just fine pre-4.0

**Comment by tigawanna** [comment]
second this,
In chrome 
this is breaking my code 
```js
        cupcake: {
          ...require("daisyui/src/theming/themes")["[data-theme=cupcake]"],
          primary: "#4f4530",
          "primary-content": "#ffffff",
          secondary: "#850a0a",
          "secondary-content": "#ffffff",
        },
```

will throw 

```sh
🌼   daisyUI 4.0.3
[postcss] Cannot read properties of undefined (reading 'l')

🌼   daisyUI 4.0.3
11:18:31 [vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'l')
  Plugin: vite:css
```

**Comment by luizkowalski** [comment]
Check this, someone might've found a fix: https://github.com/saadeghi/daisyui/issues/2496

**Comment by sveltarne** [comment]
#2496 has definately not come to a conclusion yet, as the fix of removing the data-theme part doesnt work for someone and me as well. But either way, @tigawanna, the error youre talking about is more related to #2496 than this.

**Comment by sveltarne** [comment]
I'd like to also note that i've observed the same behavior on firefox 119 android. I've observed themes working fine on safari ios (dont know what version), and on microsoft edge 119.

**Comment by mikesprague** [comment]
I'm seeing the same behavior on https://daisyui.com (and my own theme switcher implemenations). 

Works fine in Chromium-based browsers and Safari. Firefox 119 won't switch themes at all.

**Comment by alexzvn** [comment]
> i guess.. but it worked just fine pre-4.0

Turn out the `Theme Controller` component introduce an unexpected bug on Firefox.
```css
/* Firefox version less than 121 will ignore this kind of selector */
[data-theme=...], :root:has(input.theme-controller[value=...]:checked) {
    ...
}
```
The quick way to fix this is to split two selectors with duplicated content in [the build process.](https://github.com/saadeghi/daisyui/blob/4339271234c432ca083e9c0ca5e7c950fac2e61b/src/theming/functions.js#L180)

**Comment by saadeghi** [comment]
@alexzvn Thanks for addressing the issue. I will fix it as soon as I can.

**Comment by saadeghi** [comment]
Fixed in 4.0.7

**Comment by lautarocolazo** [comment]
> Fixed in 4.0.7

I updated to the latest version and now I can properly see all the themes on the official website and interact with them, and now my default theme in my project is properly working but the theme controller is still not working in Firefox. It does work perfectly in Chrome. I am a developer, but I am not super experienced with frontend so I don't exactly know how to help in this case, but if there is anything I can do to help debugging let me know.

**Comment by saadeghi** [comment]
I'm glad the issue is fixed.  
The new `theme-controller` class added in daisyUI 4 uses the new CSS `:has()` function which is not supported in Firefox yet. There's nothing we can do about it until waiting for the next Firefox version.

There's a second [on top of the page](https://daisyui.com/components/theme-controller/) it's going to work in Firefox 121+
