### ISSUE TITLE
Disable Button Pop 

### ISSUE THREAD

**Issue by giddyos** [saadeghi/daisyui#397]
How would I override the button component to disable button pop whenever the page first loads? I'm using turbolinks, and the constant animation is very distracting. 

https://github.com/saadeghi/daisyui/blob/master/src/components/styled/button.css#L4

**Comment by saadeghi** [comment]
There are 3 ways to disable or change the animation:  
- using `no-animation` class to disable animation [[docs](https://daisyui.com/components/button/)]
- changing `--animation-btn` variable on theme which is `0.25s` by default [[docs](https://daisyui.com/docs/add-themes)]
- adding some custom CSS : `.btn {animation: none;}`

Please let me know if you have any questions

**Comment by alhafoudh** [comment]
This animation is visible on every button on page on page load. It look very funny when all buttons wiggle on page load. It should be at least documented.

**Comment by saadeghi** [comment]
@alhafoudh It is documented indeed. the last example on button page: https://daisyui.com/components/button/

**Comment by alhafoudh** [comment]
@saadeghi the documentation only mentions disabling "click animation", not page load button animation.

**Comment by zicklag** [comment]
I do like the click animation, but I don't like the initial page load animation. If I had the time, would you be open to a PR to prevent the initial page load button wiggle, so that we only have movement when the user clicks the button?

**Comment by zicklag** [comment]
If I understand correctly, the issue is that DaisyUI doesn't use any JavaScript, so in order to get a button to animate, when we click it, we have to add an animation to that button, and it has to play when we stop clicking the button, so as far as I know there's not a way in CSS to get it not to play the animation when the page loads.

That said, we can use a transition instead of an animation to get an almost as nice looking effect. I added these styles to my site and it worked pretty nicely:

```css
  :root {
    --btn-focus-scale: 0.9
  }

  .btn {
    animation: none;
  }

  .btn:active {
    transition: transform 0.1s !important;
  }
```

![button-animation](https://user-images.githubusercontent.com/25393315/188210532-63cbe93d-f251-4d43-b926-02e81891849b.gif)

And now there's no page load wiggle.

**Comment by ddahan** [comment]
@zicklag not sure what's happening, but just using:

```css
  .btn {
    animation: none;
  }
```

removed the loading animation for me, while keeping the clicking animation.
Any chance it has been fixed a recent release?

**Comment by zicklag** [comment]
Interesting! I'm not sure. Maybe it's a browser thing, or maybe I didn't actually need to add the `.btn:active` class.

I'd have to update and try it again.

**Comment by dbgordon09** [comment]
Thanks @ddahan! That works beautifully.

I think there was a misunderstanding as many people have asked for this and simply received how to disable it all together as opposed to simply disabling the loading pop effect.

You can see this has been asked many times:
https://github.com/saadeghi/daisyui/issues/6
https://github.com/saadeghi/daisyui/issues/89
https://github.com/saadeghi/daisyui/issues/108

**Comment by istr** [comment]
This is still an issue. @saadeghi would you be willing to accept a PR to rework this along the proposition of @zicklag ? The problem is reproducible at least with chrome and FF, you observed and recorded it in https://github.com/saadeghi/daisyui/issues/89#issuecomment-864538161 and it makes the off-the-shelf `btn` kind of unusable for many users.

**Comment by istr** [comment]
The fix is relatively simple.

https://github.com/saadeghi/daisyui/compare/master...istr:daisyui:remove-page-load-button-pop?expand=1

@saadeghi if you re-open this issue and assign it to me, I would create a PR according to https://github.com/saadeghi/daisyui/blob/25fd6226f8c7d4523eb0b94a793c6a9df8f7d45d/.github/CONTRIBUTING.md
